#!/bin/bash
# runPM
# Automated bash script for running entire the phenotype microarray analysis
#
# Author: Daniel A Cuevas
# Created on 22 Nov. 2013
# Updated on 02 Apr. 2015

usage() {
    echo "$2

usage: $scriptname -c config_filename [Options]
OR
usage: $scriptname -i PM_data_directory -n output_directory -o output_name [Options]

Required
   -c [config_filename]    : Configuration file listing all parameters (this takes precedence)
   OR
   -i [PM_data_directory]  : PM data directory path to files
   -d [output_directory]   : Output directory (will create if non-existent)
   -o [output_name]        : Suffix appended to all output files

Optional
   --debug                 : Print out debug messages
   -e [encoding]           : Check for file encoding of original data [Default: UTF-16]
   -f                      : Flag if filter should be applied to growth curves during PManalysis
   -h, -?, --help          : This help message
   -m                      : Generate figures
   -n [number of plates]   : Number of plates [used with some parsers]
   -p [plate_filename]     : Plate filepath
   -s [sample_filename]    : Sample name and replicate file [used with some parsers]
   -t [input_file_type]    : Format number of PM plate format. Range: [1, $1]
   -v                      : Verbose output

NOTES
    FILE NAME FORMATS:
        <Sample Name>_<Replicate Letter>_<other text>.txt
        Regex used:    <Sample Name> -- [A-Za-z0-9-.]+
                       <Replicate Letter> -- [A-Za-z0-9]+

" >&2
}

error() {
    echo "*****FATAL ERROR OCCURRED*****" >&1
    echo $1 >&2
    exit 1
}

checkConfigFile() {
    configfile_secured="/tmp/PMAnalyzer_secured.cfg"
    if egrep -q -v '^#|^[^ ]*=[^;]*' "$1"; then
        getTime && echo "${currtime}    Config file is improper. Attempting to clean..." >&2
        # filter the original to a new file
        egrep '^#|^[^ ]*=[^;&]*'  "$configfile" > "$configfile_secured"
        getTime && echo "${currtime}    Cleaned config file @ ${configfile_secured}" >&2
        configfile="$configfile_secured"
    fi
    source "$configfile"
}

checkInputDirectory() {
    if [[ ! -d $1 ]]; then
        getTime && error "${currtime}    Directory '$1' does not exist."
    fi
    # Store directory in new variable and remove trailing slash
    inputfiledir=$(echo $inputfiledir | perl -ne 'chomp; s/\/$//; print;')

    inputfile=$(ls $1)
}

checkOutputDir() {
    # Remove trailing slash
    outputdir=$(echo $1 | perl -ne 'chomp; s/\/$//; print;')
    # Check to see if directory needs to be created
    [[ ! -d $1 ]] && getTime && echo "${currtime}    Output directory '$1' does not exist. Creating now." >&1 && mkdir $1
}


checkScriptDir() {
    if [[ -z $1 ]]; then
        pyscriptdir="./" # Script directory is current directory
    else
        [[ ! -d $1 ]] && getTime && error "${currtime}    Script directory '$1' does not exist."
        pyscriptdir=$1
    fi
    # Remove trailing slash
    pyscriptdir=$(echo $pyscriptdir | perl -ne 'chomp; s/\/$//; print;')
}


getTime() {
    currtime=$(date "+[%F %H:%M:%S]")
}

####################################################
#ARGUMENT PARSING
####################################################

scriptdir=$(cd $(dirname $0); pwd -P)
pyscriptdir=$(cd $(dirname $0); pwd -P)/py
plscriptdir=$(cd $(dirname $0); pwd -P)/pl
scriptname=$(echo $0 | perl -ne '/\/?.*\/(.+)/; print $1;')
filterflag=""
verboseFlag=""
debugFlag=""
imageFlag=""
numplates=""
frmtype=1
frmmax=3
samplefile=""
encoding="UTF-16"
pythonexec="/usr/local/bin/python3.4"

while [[ $# != 0 ]]; do
    case $1 in
    -h|-\?|--help)
        usage $frmmax
        exit 2
        ;;
    -c)
        shift
        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing config filename" >&2 && usage && exit 2
        configfile=$1
        ;;
    -d)
        shift
        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -d value" >&2 && usage && exit 2
        outputdir=$1
        ;;
    --debug)
        debugFlag="--debug"
        ;;
    -e)
        shift
        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -d value" >&2 && usage && exit 2
        encoding=$1
        ;;
    -f)
        filterflag="-f"
        ;;
    -i)
        shift
        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -i value" >&2 && usage && exit 2
        inputfiledir=$1
        ;;
    -m)
        imageFlag="-i"
        ;;
    -n)
        shift
        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -n value" >&2 && usage && exit 2
        numplates=$1
        ;;
    -o)
        shift
        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -o value" >&2 && usage && exit 2
        outputname=$1
        ;;
    -p)
        shift
        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -p value" >&2 && usage && exit 2
        plate=$1
        ;;
    -s)
        shift
        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -s value" >&2 && usage && exit 2
        samplefile=$1
        ;;
    -t)
        shift
        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -t value" >&2 && usage && exit 2
        frmtype=$1
        ;;
    -v)
        verbose=0;
        verboseFlag="-v"
        ;;
    *)
        echo "Unknown option $1" >&2
        usage $frmmax
        exit 2
    esac
    shift
done

# Check if config file was supplied
if [[ $configfile ]]; then
    checkConfigFile $configfile
fi

# Check if required variables are set
if [[ ! $inputfiledir ||
    ! $outputname ||
    ! $outputdir ]]; then
    usage $frmmax "Missing one or more required arguments."
    exit 2
fi

if [[ $frmtype -eq 3 ]] &&
    [[ ! $numplates || ! $samplefile ]]; then
    usage $frmmax "Missing -n and/or -s options."
    exit 2
fi


# Set internal field separator for files with spaces
SAVEIFS=$IFS
IFS=$(echo -en '\n\b')

# Check if input file or directory exists
checkInputDirectory $inputfiledir

# Remove leading slashes from output directory
checkOutputDir $outputdir

# Check if script direectory exists
checkScriptDir $pyscriptdir

# Check for UTF-8 encodings
getTime && echo "${currtime}    *****Checking character encodings*****" >&1
for f in ${inputfile[@]}; do
    enc=$(file --mime "$inputfiledir/$f" | egrep -ic "utf-8|us-ascii")
    if [[ $enc -eq 0 ]]; then
        f=$(echo "$f" | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
        cmd="iconv -f $encoding -t UTF-8 \"$inputfiledir/$f\" > tmp.txt && mv tmp.txt \"$inputfiledir/$f\""
        [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
        eval $cmd
        [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
    fi
done

# Convert input files line endings from DOS to UNIX
getTime && echo "${currtime}    *****Checking line endings*****" >&1
for f in ${inputfile[@]}; do
    f=$(echo "$f" | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
    cmd="perl -i -pe 's/\r\n?/\n/g' \"$inputfiledir/$f\""
    [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
    eval $cmd
    [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
done

# Check which parser to use
case $frmtype in
    1)
        p_script="pmParser.pl"
        ;;
    2)
        p_script="well_vs_time_parser.pl"
        ;;
    3)
        p_script="pmParser_v2.pl -n $numplates -s \"$samplefile\""
        ;;
    *)
        echo "Format type must be an integer within the range [1, $frmmax]." >&2
        usage $frmmax
        exit 2
esac

################################################
#ANALYST PARSING
################################################

getTime && echo "${currtime}    *****Parsing analyst files*****" >&1
out="raw_curves_${outputname}.txt"

# Check if plate was supplied
if [[ $plate ]]; then
    cmd="${plscriptdir}/${p_script} -d $inputfiledir -p $plate > $outputdir/${out}"
else
    cmd="${plscriptdir}/${p_script} -d $inputfiledir > $outputdir/${out}"
fi
[[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
eval $cmd
[[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"

################################################
#ANALYSIS
################################################

in="$outputdir/${out}"
if [[ $plate ]]; then
    cmd="$pythonexec ${pyscriptdir}/pmanalysis.py $in $outputdir -o $outputname -p $filterflag $verboseFlag $debugFlag $imageFlag"
else
    cmd="$pythonexec ${pyscriptdir}/pmanalysis.py $in $outputdir -o $outputname $filterflag $verboseFlag $debugFlag $imageFlag"
fi
getTime && echo "${currtime}    *****Starting modeling script*****" >&1
[[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
eval $cmd
[[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"

# Restore internal field separator
IFS=$SAVEIFS
getTime && echo "${currtime}    *****Completed!*****" >&1
